production: true
services:
  backend:
    image:
      repository: ghcr.io/Effloresc3/pdep-bot-app
      source:
        type: registry
        allowTags: ^latest$ 
    # secrets:
    #   - config
    routes:
      - host: pdepbot.ludat.io

