production: true
services:
  backend:
    image:
      repository: ghcr.io/effloresc3/pdep-bot-app
      source:
        type: digest 
        tag: latest
    # secrets:
    #   - config
    routes:
      - host: pdepbot.ludat.io

